backend:
  image: shreybatra/sample-backend
  service:
    type: ClusterIP
    port: 8000

frontend:
  image: shreybatra/sample-frontend
  service:
    type: NodePort
    port: 5173
    nodePort: 31000

redis:
  image: redis
  service:
    type: ClusterIP
    port: 6379
